# Generated by Django 5.1.4 on 2025-01-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mebros', '0001_initial'),
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='mebros.member')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='treino.training')),
            ],
        ),
    ]
